use_frameworks!

target 'NSMLikeView_Example' do
  pod 'NSMLikeView', :path => '../'

  target 'NSMLikeView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
